(() => {
'use strict';
const S=window.ProjectStorage;
const ProjectService=window.ProjectService;
const params=new URLSearchParams(location.search);let currentProjectId=params.get('project');let currentProjectTitle='Modelo 1';
const PALETTE=[['Verde petróleo','#014744'],['Verde médio','#5B7E4E'],['Verde suave','#C4C9B3'],['Grafite','#262E34'],['Creme','#F3F0EB']];
const BOX_PALETTES={
  light:{name:'Claro',bg:'#DFDDD2',title:'#014744',text:'#262E34',circle:'#C4C9B3',icon:'#F3F0EB'},
  dark:{name:'Escuro',bg:'#014744',title:'#C4C9B3',text:'#F3F0EB',circle:'#F3F0EB',icon:'#014744'}
};
const clone=o=>JSON.parse(JSON.stringify(o));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const defaultBox=()=>({titleHtml:'O que é?',bodyHtml:'É um procedimento minimamente invasivo que cria microperfurações controladas no couro cabeludo para estimular a regeneração tecidual e potencializar a absorção de ativos.',palette:'light',icon:{type:'asset',src:'assets/modelo1/layer-14.png',name:'Ícone original'}});
const defaults={version:5,fileName:'Modelo 1',titleMainHtml:'Microagulhamento na',titleHighlightHtml:'Tricologia',titleSize:58,titleAutoFit:true,subtitleHtml:'Uma técnica minimamente invasiva que promove estímulos importantes para a saúde do couro cabeludo e dos fios.',boxes:[defaultBox()],benefitTitleHtml:'Principais benefícios',bodyHtml:'Estimular o crescimento dos fios<br>Melhorar a circulação sanguínea<br>Aumentar a absorção de ativos<br>Fortalecer fios enfraquecidos<br>Recuperar a densidade capilar<br>Reduzir queda<br>Estimular regeneração tecidual<br>Melhorar aparência de cicatrizes',bodyIsList:true,additionalInfoHtml:'O MICROAGULHAMENTO É UMA FERRAMENTA TERAPÊUTICA SEGURA E É BASEADA EM EVIDÊNCIAS PARA MELHORAR A SAÚDE DO COURO CABELUDO E POTENCIALIZAR TRATAMENTOS CAPILARES.',image:{src:'assets/modelo1/layer-16.png',offsetX:0,offsetY:0,zoom:1}};
function merge(a,b){const o=clone(a);for(const[k,v]of Object.entries(b||{})){if(Array.isArray(v))o[k]=clone(v);else if(v&&typeof v==='object'&&o[k]&&typeof o[k]==='object'&&!Array.isArray(o[k]))o[k]=merge(o[k],v);else o[k]=v}return o}
function migrate(x){x=merge(defaults,x||{});if(x.titleHtml&&!x.titleMainHtml){const tmp=document.createElement('div');tmp.innerHTML=x.titleHtml;const text=tmp.textContent||'Microagulhamento na Tricologia';const p=text.lastIndexOf(' ');x.titleMainHtml=esc(p>0?text.slice(0,p):text);x.titleHighlightHtml=esc(p>0?text.slice(p+1):'Tricologia')}if(x.infoHtml&&!x.additionalInfoHtml)x.additionalInfoHtml=x.infoHtml;x.boxes=(x.boxes||[defaultBox()]).map(b=>({...defaultBox(),...b,icon:b.icon&&typeof b.icon==='object'?b.icon:defaultBox().icon}));x.fileName='Modelo 1';return x}
const projectKey=id=>`modelo1:project:${id}`,draftKey=()=>currentProjectId?projectKey(currentProjectId):'modelo1:draft';


const $=id=>document.getElementById(id);
const els={titleMain:$('titleMain'),titleHighlight:$('titleHighlight'),titleSize:$('titleSize'),titleSizeOut:$('titleSizeOut'),titleAutoFit:$('titleAutoFit'),subtitle:$('subtitle'),benefitTitle:$('benefitTitle'),bodyCopy:$('bodyCopy'),bodyIsList:$('bodyIsList'),additionalInfo:$('additionalInfo'),boxEditors:$('boxEditors'),addBox:$('addBox'),imageUpload:$('imageUpload'),imageZoom:$('imageZoom'),imageZoomOut:$('imageZoomOut'),resetImage:$('resetImage'),exportFormat:$('exportFormat'),exportFile:$('exportFile'),saveProject:$('saveProject'),duplicateProject:$('duplicateProject'),projectFeedback:$('projectFeedback'),design:$('design'),stageWrap:document.querySelector('.stage-wrap'),previewTitle:$('previewTitle'),previewTitleMain:$('previewTitleMain'),previewTitleHighlight:$('previewTitleHighlight'),previewSubtitle:$('previewSubtitle'),previewBoxes:$('previewBoxes'),lowerFlow:$('lowerFlow'),previewBenefitTitle:$('previewBenefitTitle'),previewBodyCopy:$('previewBodyCopy'),previewAdditionalInfo:$('previewAdditionalInfo'),imageMask:$('imageMask'),previewImage:$('previewImage')};
let state=clone(defaults);
async function loadState(){await S?.ready;const p=currentProjectId?await ProjectService.get(currentProjectId):null;if(p?.title)currentProjectTitle=p.title;const d=await S?.getAsync?.(draftKey(),null);state=migrate((p?.state)||d||defaults)}

// Rich text selection toolbar
const savedRanges=new WeakMap();
function saveRange(ed){const sel=getSelection();if(!sel?.rangeCount)return;const r=sel.getRangeAt(0);if(ed.contains(r.commonAncestorContainer))savedRanges.set(ed,r.cloneRange())}
function applyStyle(ed,prop,val,onChange){const r=savedRanges.get(ed);if(!r||r.collapsed){feedback('Selecione um trecho do texto primeiro.');return}const span=document.createElement('span');span.style[prop]=val;try{span.appendChild(r.extractContents());r.insertNode(span);const sel=getSelection();sel.removeAllRanges();const nr=document.createRange();nr.selectNodeContents(span);sel.addRange(nr);savedRanges.set(ed,nr.cloneRange());onChange(ed.innerHTML);commit()}catch(e){console.error(e)}}
function toolbarHTML(){return `<div class="rt-colors">${PALETTE.map(([n,v])=>`<button type="button" class="rt-swatch" data-color="${v}" title="${n}" style="background:${v}"></button>`).join('')}</div><select class="rt-weight" title="Peso"><option value="400">Regular</option><option value="500">Medium</option><option value="600">Semibold</option><option value="700">Bold</option></select><select class="rt-size" title="Tamanho"><option value="14px">14</option><option value="16px">16</option><option value="18px" selected>18</option><option value="20px">20</option><option value="24px">24</option><option value="28px">28</option><option value="32px">32</option><option value="36px">36</option><option value="40px">40</option><option value="48px">48</option><option value="58px">58</option><option value="64px">64</option><option value="72px">72</option></select>`}
function wireRich(ed,toolbar,onChange){toolbar.innerHTML=toolbarHTML();['mouseup','keyup','focus','input'].forEach(ev=>ed.addEventListener(ev,()=>{saveRange(ed);if(ev==='input'){onChange(ed.innerHTML);commit()}}));toolbar.querySelectorAll('.rt-swatch').forEach(b=>b.addEventListener('mousedown',e=>{e.preventDefault();applyStyle(ed,'color',b.dataset.color,onChange)}));const w=toolbar.querySelector('.rt-weight'),z=toolbar.querySelector('.rt-size');[w,z].forEach(x=>x.addEventListener('pointerdown',()=>saveRange(ed)));w.onchange=()=>applyStyle(ed,'fontWeight',w.value,onChange);z.onchange=()=>applyStyle(ed,'fontSize',z.value,onChange)}
function wireStaticRich(){wireRich(els.titleMain,document.querySelector('[data-toolbar-for="titleMain"]'),v=>state.titleMainHtml=v);wireRich(els.titleHighlight,document.querySelector('[data-toolbar-for="titleHighlight"]'),v=>state.titleHighlightHtml=v);wireRich(els.subtitle,document.querySelector('[data-toolbar-for="subtitle"]'),v=>state.subtitleHtml=v);wireRich(els.benefitTitle,document.querySelector('[data-toolbar-for="benefitTitle"]'),v=>state.benefitTitleHtml=v);wireRich(els.bodyCopy,document.querySelector('[data-toolbar-for="bodyCopy"]'),v=>state.bodyHtml=v);wireRich(els.additionalInfo,document.querySelector('[data-toolbar-for="additionalInfo"]'),v=>state.additionalInfoHtml=v)}

function feedback(msg){els.projectFeedback.textContent=msg}
async function persist(){state.updatedAt=new Date().toISOString();if(S?.setAsync)await S.setAsync(draftKey(),clone(state));else S?.set(draftKey(),clone(state));feedback(S?.persistent?'Alterações salvas automaticamente.':'Alterações preservadas nesta sessão.')}
let persistTimer=null;function queuePersist(){clearTimeout(persistTimer);persistTimer=setTimeout(()=>persist(),180)}
function commit(){renderPreview();queuePersist()}
function syncInputs(){els.titleMain.innerHTML=state.titleMainHtml;els.titleHighlight.innerHTML=state.titleHighlightHtml;els.subtitle.innerHTML=state.subtitleHtml;els.benefitTitle.innerHTML=state.benefitTitleHtml;els.bodyCopy.innerHTML=state.bodyHtml;els.additionalInfo.innerHTML=state.additionalInfoHtml;els.titleSize.value=state.titleSize;els.titleSizeOut.textContent=state.titleSize+'px';els.titleAutoFit.checked=state.titleAutoFit;els.bodyIsList.checked=state.bodyIsList;els.imageZoom.value=state.image.zoom;renderBoxEditors()}

function colorizeSvg(svg){return String(svg||'').replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<foreignObject[\s\S]*?<\/foreignObject>/gi,'').replace(/\son\w+="[^"]*"/gi,'').replace(/\s(fill|stroke)="(?!none)[^"]*"/gi,' $1="currentColor"').replace('<svg','<svg class="uploaded-svg"')}
function iconMarkup(icon){if(!icon)icon={type:'asset',src:'assets/modelo1/layer-14.png'};if(icon.type==='svg')return colorizeSvg(icon.data);const src=icon.data||icon.src||'assets/modelo1/layer-14.png';return `<span class="uploaded-icon-mask" style="--icon-mask:url('${src}')"></span>`}
function readIconFile(file){return new Promise((resolve,reject)=>{const name=file.name||'Ícone';if(file.type==='image/svg+xml'||/\.svg$/i.test(name)){const r=new FileReader();r.onload=()=>resolve({type:'svg',data:r.result,name});r.onerror=reject;r.readAsText(file)}else if(file.type==='image/png'||/\.png$/i.test(name)){const r=new FileReader();r.onload=()=>resolve({type:'png',data:r.result,name});r.onerror=reject;r.readAsDataURL(file)}else reject(new Error('Envie um SVG ou PNG.'))})}
function renderBoxEditors(){els.boxEditors.innerHTML='';state.boxes.forEach((box,index)=>{const w=document.createElement('section');w.className='box-editor';w.innerHTML=`<div class="box-editor-head"><strong>Box ${index+1}</strong><div class="icon-actions"><button type="button" class="mini duplicate">Duplicar</button>${state.boxes.length>1?'<button type="button" class="mini danger remove">Excluir</button>':''}</div></div><div class="field rich-field"><span>Título</span><div class="rich-input box-title" contenteditable="true"></div><div class="rich-toolbar title-toolbar"></div></div><div class="field rich-field"><span>Texto</span><div class="rich-input rich-input-tall box-body" contenteditable="true"></div><div class="rich-toolbar body-toolbar"></div></div><div class="palette-field"><span>Paleta do box</span><div class="palette-options"></div></div><label class="field icon-upload-field"><span>Ícone do box</span><input class="box-icon-file" type="file" accept=".svg,.png,image/svg+xml,image/png"><small>${esc(box.icon?.name||'Ícone original do PSD')}</small></label>`;
const te=w.querySelector('.box-title'),be=w.querySelector('.box-body');te.innerHTML=box.titleHtml;be.innerHTML=box.bodyHtml;wireRich(te,w.querySelector('.title-toolbar'),v=>box.titleHtml=v);wireRich(be,w.querySelector('.body-toolbar'),v=>box.bodyHtml=v);
const po=w.querySelector('.palette-options');Object.entries(BOX_PALETTES).forEach(([k,p])=>{const b=document.createElement('button');b.type='button';b.className='palette-card'+(box.palette===k?' is-selected':'');b.innerHTML=`<span class="palette-preview"><i style="background:${p.bg}"></i><i style="background:${p.title}"></i><i style="background:${p.text}"></i></span>${p.name}`;b.onclick=()=>{box.palette=k;renderBoxEditors();commit()};po.appendChild(b)});
w.querySelector('.box-icon-file').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{box.icon=await readIconFile(f);renderBoxEditors();commit()}catch(err){alert(err.message)}};
w.querySelector('.duplicate').onclick=()=>{if(state.boxes.length>=2){feedback('Limite de 2 boxes atingido para preservar a legibilidade.');return}state.boxes.splice(index+1,0,clone(box));renderBoxEditors();commit()};w.querySelector('.remove')?.addEventListener('click',()=>{state.boxes.splice(index,1);renderBoxEditors();commit()});els.boxEditors.appendChild(w)})}

function renderPreview(){els.previewTitleMain.innerHTML=state.titleMainHtml;els.previewTitleHighlight.innerHTML=state.titleHighlightHtml;els.previewSubtitle.innerHTML=state.subtitleHtml;els.previewBenefitTitle.innerHTML=state.benefitTitleHtml;els.previewAdditionalInfo.innerHTML=state.additionalInfoHtml;els.previewTitle.style.fontSize=state.titleSize+'px';fitTitle();els.previewBodyCopy.classList.toggle('is-list',state.bodyIsList);if(state.bodyIsList){const lines=htmlToRichLines(state.bodyHtml);els.previewBodyCopy.innerHTML='';lines.forEach(line=>{const d=document.createElement('div');d.className='body-line';d.innerHTML=`<span class="body-check" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M5 12.5l4 4L19 6.5" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg></span><span>${line}</span>`;els.previewBodyCopy.appendChild(d)})}else els.previewBodyCopy.innerHTML=state.bodyHtml;els.previewBoxes.innerHTML='';state.boxes.forEach(box=>{const p=BOX_PALETTES[box.palette]||BOX_PALETTES.light,d=document.createElement('section');d.className='design-box';d.style.background=p.bg;d.innerHTML=`<div class="design-box-icon-wrap" style="background:${p.circle};color:${p.icon}">${iconMarkup(box.icon)}</div><div class="design-box-copy"><h3 style="color:${p.title}">${box.titleHtml}</h3><div class="box-body-preview" style="color:${p.text}">${box.bodyHtml}</div></div>`;els.previewBoxes.appendChild(d)});els.previewImage.src=state.image.src;els.previewImage.style.transform=`translate(${state.image.offsetX}px,${state.image.offsetY}px) scale(${state.image.zoom})`;els.imageZoomOut.textContent=Math.round(state.image.zoom*100)+'%';requestAnimationFrame(layoutFlow)}
function htmlToRichLines(html){
  const root=document.createElement('div');
  root.innerHTML=html||'';
  const blockTags=new Set(['DIV','P','LI','H1','H2','H3','H4','H5','H6']);
  const lines=[];
  let buffer='';
  const flush=()=>{const probe=document.createElement('div');probe.innerHTML=buffer;const text=(probe.textContent||'').replace(/\u00a0/g,' ').trim();if(text)lines.push(buffer.trim());buffer=''};
  const splitBlock=(node)=>{
    const holder=document.createElement('div');
    holder.innerHTML=node.innerHTML;
    const parts=[];let part='';
    [...holder.childNodes].forEach(child=>{
      if(child.nodeName==='BR'){const probe=document.createElement('div');probe.innerHTML=part;if((probe.textContent||'').trim())parts.push(part.trim());part='';}
      else part+=child.nodeType===Node.TEXT_NODE?esc(child.textContent):child.outerHTML;
    });
    const probe=document.createElement('div');probe.innerHTML=part;if((probe.textContent||'').trim())parts.push(part.trim());
    return parts;
  };
  [...root.childNodes].forEach(node=>{
    if(node.nodeName==='BR'){flush();return}
    if(node.nodeType===Node.ELEMENT_NODE&&blockTags.has(node.nodeName)){
      flush();splitBlock(node).forEach(x=>lines.push(x));return;
    }
    if(node.nodeType===Node.TEXT_NODE){
      const chunks=(node.textContent||'').split(/\r?\n/);
      chunks.forEach((chunk,i)=>{buffer+=esc(chunk);if(i<chunks.length-1)flush()});
    } else if(node.outerHTML) buffer+=node.outerHTML;
  });
  flush();
  if(!lines.length){const text=(root.innerText||root.textContent||'').split(/\r?\n+/).map(x=>x.trim()).filter(Boolean);return text.map(esc)}
  return lines;
}
function fitTitle(){let z=state.titleSize;els.previewTitle.style.fontSize=z+'px';if(state.titleAutoFit){while(z>28&&els.previewTitle.scrollWidth>els.previewTitle.clientWidth){z--;els.previewTitle.style.fontSize=z+'px'}}}
function layoutFlow(){
  const designScale=els.design.getBoundingClientRect().width/1080||1;
  const subtitleHeight=els.previewSubtitle.getBoundingClientRect().height/designScale;
  const boxTop=346+subtitleHeight+32;
  els.previewBoxes.style.top=boxTop+'px';
  const boxes=[...els.previewBoxes.children];
  const baseGap=43, benefitGap=128, maxBenefitTop=1127, MIN_DENSITY=.88;
  boxes.forEach(n=>{n.style.setProperty('--box-scale','1');n.style.top='0px';n.style.width='954px'});
  let naturalHeights=boxes.map(n=>n.offsetHeight||265);
  let naturalTotal=naturalHeights.reduce((a,b)=>a+b,0)+Math.max(0,boxes.length-1)*baseGap;
  const available=Math.max(265,maxBenefitTop-benefitGap-boxTop);
  const needed=naturalTotal>available?available/naturalTotal:1;
  const density=Math.max(MIN_DENSITY,Math.min(1,needed));
  boxes.forEach(n=>n.style.setProperty('--box-scale',String(density)));
  const heights=boxes.map(n=>n.offsetHeight||265*density),gap=baseGap*density;
  let y=0;boxes.forEach((n,i)=>{n.style.top=y+'px';y+=heights[i];if(i<boxes.length-1)y+=gap});
  els.previewBoxes.style.height=Math.max(0,y)+'px';els.previewBoxes.dataset.scale=density.toFixed(3);
  const benefitTop=boxTop+y+benefitGap;
  els.lowerFlow.style.setProperty('--lower-offset',(benefitTop-1127)+'px');
  els.design.style.height='1920px';updateScale();
  const overflow=naturalTotal*density>available+2;
  els.addBox.disabled=state.boxes.length>=2||overflow;
  els.addBox.title=state.boxes.length>=2?'Limite de boxes atingido para preservar a legibilidade.':'';
  if(overflow)feedback('O conteúdo atingiu o limite seguro dos boxes. Reduza o texto antes de adicionar outro box.');
}
function updateScale(){const sc=Math.min((els.stageWrap.clientWidth||720)/1080,1);els.design.style.transform=`scale(${sc})`;els.stageWrap.style.height=1920*sc+'px'}

function newId(){return `modelo1-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`}
async function makeProjectSnapshot(){try{const source=await renderCanvas();const c=document.createElement('canvas');c.width=360;c.height=640;c.getContext('2d').drawImage(source,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.82)}catch(e){console.warn('snapshot',e);return null}}
async function askProjectName(mode){return await window.ProjectNameDialog?.open({title:mode==='duplicate'?'Duplicar projeto':'Salvar projeto',description:mode==='duplicate'?'Dê um nome para a nova cópia. O projeto original será preservado.':'Dê um nome para identificar este projeto no index.',value:mode==='duplicate'?`${currentProjectTitle||'Modelo 1'} - cópia`:(currentProjectTitle||'Modelo 1'),confirmText:mode==='duplicate'?'Criar cópia':'Salvar'})}
async function saveProject(){try{await S?.ready;const name=await askProjectName('save');if(!name)return null;if(!currentProjectId)currentProjectId=newId();const now=new Date().toISOString();const old=await ProjectService.get(currentProjectId);const previewData=await makeProjectSnapshot();const rec={id:currentProjectId,template:'modelo1isa',title:name,fileName:name,previewData,preview:old?.preview||'assets/images/modelo1-preview.jpg',editor:`modelo-editor.html?project=${encodeURIComponent(currentProjectId)}`,savedAt:old?.savedAt||now,updatedAt:now,state:clone(state)};await ProjectService.save(rec);currentProjectTitle=name;if(S?.setAsync)await S.setAsync(projectKey(currentProjectId),clone(state));else S?.set?.(projectKey(currentProjectId),clone(state));history.replaceState({},'',`modelo-editor.html?project=${encodeURIComponent(currentProjectId)}`);flash(els.saveProject,'Salvo ✓');feedback(`Projeto “${name}” salvo e disponível no index.`);return currentProjectId}catch(e){console.error(e);feedback('Erro ao salvar projeto: '+e.message);return null}}
async function duplicateProject(){try{await S?.ready;const name=await askProjectName('duplicate');if(!name)return null;const source=currentProjectId||null,id=newId(),now=new Date().toISOString(),copy=clone(state),previewData=await makeProjectSnapshot();const rec={id,template:'modelo1isa',title:name,fileName:name,previewData,preview:'assets/images/modelo1-preview.jpg',editor:`modelo-editor.html?project=${encodeURIComponent(id)}`,savedAt:now,updatedAt:now,duplicatedFrom:source||undefined,state:copy};await ProjectService.save(rec);if(S?.setAsync)await S.setAsync(projectKey(id),copy);else S?.set?.(projectKey(id),copy);currentProjectId=id;currentProjectTitle=name;history.replaceState({},'',`modelo-editor.html?project=${encodeURIComponent(id)}`);flash(els.duplicateProject,'Cópia criada ✓');feedback(`Cópia “${name}” criada. O original foi preservado.`);return id}catch(e){console.error(e);feedback('Erro ao duplicar projeto: '+e.message);return null}}
function flash(b,t){const o=b.dataset.old||b.textContent;b.dataset.old=o;b.textContent=t;b.classList.add('is-success');setTimeout(()=>{b.textContent=o;b.classList.remove('is-success')},1400)}
function safeName(s){return String(s||'Modelo 1').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').toLowerCase()||'modelo-1'}
function fileToResizedDataURL(file,max){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.9))};im.onerror=rej;im.src=r.result};r.onerror=rej;r.readAsDataURL(file)})}
async function handleImageUpload(e){const f=e.target.files?.[0];if(!f)return;state.image={src:await fileToResizedDataURL(f,1400),offsetX:0,offsetY:0,zoom:1};els.imageZoom.value=1;commit()}
function wireImageDrag(){let d=null;els.imageMask.onpointerdown=e=>{d={x:e.clientX,y:e.clientY,ox:state.image.offsetX,oy:state.image.offsetY};els.imageMask.setPointerCapture(e.pointerId)};els.imageMask.onpointermove=e=>{if(!d)return;const sc=els.design.getBoundingClientRect().width/1080||1;state.image.offsetX=d.ox+(e.clientX-d.x)/sc;state.image.offsetY=d.oy+(e.clientY-d.y)/sc;renderPreview()};els.imageMask.onpointerup=els.imageMask.onpointercancel=()=>{if(d){d=null;queuePersist()}}}
function wire(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('is-active',x===b));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('is-active',p.dataset.panelContent===b.dataset.panel))});els.titleSize.oninput=e=>{state.titleSize=+e.target.value;els.titleSizeOut.textContent=e.target.value+'px';commit()};els.titleAutoFit.onchange=e=>{state.titleAutoFit=e.target.checked;commit()};els.bodyIsList.onchange=e=>{state.bodyIsList=e.target.checked;commit()};els.imageZoom.oninput=e=>{state.image.zoom=+e.target.value;commit()};els.addBox.onclick=()=>{if(state.boxes.length>=2){feedback('Limite de 2 boxes atingido para preservar a legibilidade.');return}state.boxes.push(defaultBox());renderBoxEditors();commit()};els.resetImage.onclick=()=>{state.image.offsetX=0;state.image.offsetY=0;state.image.zoom=1;els.imageZoom.value=1;commit()};els.imageUpload.onchange=handleImageUpload;els.saveProject.onclick=saveProject;els.duplicateProject.onclick=duplicateProject;els.exportFormat.onchange=()=>els.exportFile.textContent=`Baixar ${els.exportFormat.value.toUpperCase()}`;els.exportFile.onclick=exportFile;addEventListener('resize',updateScale);wireImageDrag();wireStaticRich()}

// Export fixed to original PSD dimensions: 1080 × 1920.
async function blobDataURL(url){if(/^data:/.test(url))return url;const r=await fetch(url);const b=await r.blob();return await new Promise((res,rej)=>{const f=new FileReader();f.onload=()=>res(f.result);f.onerror=rej;f.readAsDataURL(b)})}
async function renderCanvas(){await document.fonts.ready;const cloneNode=els.design.cloneNode(true);cloneNode.style.transform='none';cloneNode.style.width='1080px';cloneNode.style.height='1920px';cloneNode.style.position='relative';const imgs=[...cloneNode.querySelectorAll('img')];await Promise.all(imgs.map(async i=>{try{i.src=await blobDataURL(i.getAttribute('src'))}catch{}}));const css=[...document.styleSheets].map(ss=>{try{return [...ss.cssRules].map(r=>r.cssText).join('\n')}catch{return''}}).join('\n');const html=new XMLSerializer().serializeToString(cloneNode),svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920"><foreignObject width="1080" height="1920"><div xmlns="http://www.w3.org/1999/xhtml"><style>${css}</style>${html}</div></foreignObject></svg>`;const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const im=await new Promise((res,rej)=>{const x=new Image();x.onload=()=>res(x);x.onerror=rej;x.src=url});const c=document.createElement('canvas');c.width=1080;c.height=1920;c.getContext('2d').drawImage(im,0,0);return c}finally{URL.revokeObjectURL(url)}}
function toBlob(c,t,q){return new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('Falha ao exportar')),t,q))}
function dl(blob,name){const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1200)}
function jpegPdf(jpeg,w,h){const E=s=>new TextEncoder().encode(s),parts=[],offs=[0];let pos=0;const push=b=>{parts.push(b);pos+=b.length},obj=(n,a)=>{offs[n]=pos;push(E(`${n} 0 obj\n`));a.forEach(p=>push(typeof p==='string'?E(p):p));push(E('\nendobj\n'))};push(E('%PDF-1.4\n'));obj(1,['<< /Type /Catalog /Pages 2 0 R >>']);obj(2,['<< /Type /Pages /Kids [3 0 R] /Count 1 >>']);const pw=405,ph=pw*h/w;obj(3,[`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pw} ${ph}] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>`]);obj(4,[`<< /Type /XObject /Subtype /Image /Width ${w} /Height ${h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`,jpeg,'\nendstream']);const q=`q\n${pw} 0 0 ${ph} 0 0 cm\n/Im0 Do\nQ\n`;obj(5,[`<< /Length ${q.length} >>\nstream\n${q}endstream`]);const x=pos;push(E('xref\n0 6\n0000000000 65535 f \n'));for(let i=1;i<=5;i++)push(E(`${String(offs[i]).padStart(10,'0')} 00000 n \n`));push(E(`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`));return new Blob(parts,{type:'application/pdf'})}
async function exportFile(){els.exportFile.disabled=true;try{const c=await renderCanvas(),fmt=els.exportFormat.value,base=safeName('Modelo 1');if(fmt==='png')dl(await toBlob(c,'image/png',1),base+'.png');else if(fmt==='jpg')dl(await toBlob(c,'image/jpeg',.95),base+'.jpg');else{const b=await toBlob(c,'image/jpeg',.95);dl(jpegPdf(new Uint8Array(await b.arrayBuffer()),1080,1920),base+'.pdf')}}catch(e){console.error(e);alert('Não foi possível exportar: '+e.message)}finally{els.exportFile.disabled=false;els.exportFile.textContent=`Baixar ${els.exportFormat.value.toUpperCase()}`}}

(async function init(){await loadState();syncInputs();wire();renderPreview();updateScale();await persist()})();
})();
