(() => {
  'use strict';
  const PROJECTS_KEY='prescricao-editor:projects:v1';
  const DRAFT_KEY='modelo1:draft:v2';
  const PROJECT_DRAFT_PREFIX='modelo1:project-draft:';
  const params=new URLSearchParams(location.search);
  let currentProjectId=params.get('project');

  const PALETTE=[
    {name:'Verde petróleo',value:'#014744'},
    {name:'Verde médio',value:'#5B7E4E'},
    {name:'Verde suave',value:'#C4C9B3'},
    {name:'Grafite',value:'#262E34'},
    {name:'Creme',value:'#F3F0EB'}
  ];
  const BOX_PALETTES={
    light:{name:'Claro',bg:'#DFDDD2',title:'#014744',text:'#262E34',circle:'#C4C9B3',icon:'#FFFFFF'},
    dark:{name:'Escuro',bg:'#014744',title:'#C4C9B3',text:'#F3F0EB',circle:'#5B7E4E',icon:'#F3F0EB'}
  };
  const ICONS=[
    {name:'favorite',label:'Coração',path:'M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09A6.01 6.01 0 0 1 16.5 3C19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54z'},
    {name:'check_circle',label:'Check',path:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zm-2 15-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z'},
    {name:'health_and_safety',label:'Saúde',path:'M12 2 4 5v6c0 5.05 3.41 9.76 8 11 4.59-1.24 8-5.95 8-11V5l-8-3zm4 11h-3v3h-2v-3H8v-2h3V8h2v3h3v2z'},
    {name:'medical_services',label:'Médico',path:'M19 6h-3V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v2H5a3 3 0 0 0-3 3v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a3 3 0 0 0-3-3zm-9-2h4v2h-4V4zm5 10h-2v2h-2v-2H9v-2h2v-2h2v2h2v2z'},
    {name:'science',label:'Ciência',path:'M9 2v2h1v5.59l-5.7 7.32A3.2 3.2 0 0 0 6.82 22h10.36a3.2 3.2 0 0 0 2.52-5.09L14 9.59V4h1V2H9zm3 9.1 2.25 2.9h-4.5L12 11.1z'},
    {name:'spa',label:'Spa',path:'M12 21c-4.42 0-8-3.58-8-8 4.42 0 8 3.58 8 8zm0 0c0-4.42 3.58-8 8-8 0 4.42-3.58 8-8 8zm0-8c-2.76 0-5-2.24-5-5 2.76 0 5 2.24 5 5zm0 0c0-2.76 2.24-5 5-5 0 2.76-2.24 5-5 5z'},
    {name:'healing',label:'Cuidado',path:'M17.73 12.73 12 18.46l-5.73-5.73a6 6 0 0 1 8.49-8.49L12 7l-2.76-2.76a6 6 0 0 1 8.49 8.49z'},
    {name:'water_drop',label:'Gota',path:'M12 2s-7 7.24-7 12a7 7 0 0 0 14 0c0-4.76-7-12-7-12zm0 16a4 4 0 0 1-4-4c0-.78.32-1.72.82-2.7A6 6 0 0 0 15 17.18 3.98 3.98 0 0 1 12 18z'},
    {name:'eco',label:'Folha',path:'M17.5 3C12 3 7.5 5 5 9c-2 3.2-1.4 7.2 1.4 9.5C9.2 20.8 13.2 20 15 17c2.6-4.2 1.7-9.7 2.5-14zM7 17c2-5 5-8 9-11-3 4-5 7-6 12l-3-1z'},
    {name:'bolt',label:'Energia',path:'M11 21h-1l1-7H7.5c-.88 0-.33-.75-.31-.78C8.48 10.94 10.42 7.54 13 3h1l-1 7h3.5c.4 0 .62.19.4.66C12.97 17.53 11 21 11 21z'},
    {name:'star',label:'Estrela',path:'m12 17.27 6.18 3.73-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z'},
    {name:'psychology',label:'Bem-estar',path:'M13 3a5 5 0 0 0-4.9 4H7a4 4 0 0 0-1 7.87V17a4 4 0 0 0 7.87 1H15a4 4 0 0 0 1-7.87V8a5 5 0 0 0-3-5zm-1 12H9v-2h3v2zm3-4H9V9h6v2z'}
  ];
  const defaultBox=()=>({title:'O que é?',body:'É um procedimento minimamente invasivo que cria microperfurações controladas no couro cabeludo para estimular a regeneração tecidual e potencializar a absorção de ativos.',palette:'light',icon:'favorite'});
  const defaults={
    version:2,fileName:'Modelo 1',title:'Microagulhamento na Tricologia',titleSize:58,titleAutoFit:true,titleColor:'#014744',titleAccentColor:'#5B7E4E',
    subtitle:'Uma técnica minimamente invasiva que promove estímulos importantes para a saúde do couro cabeludo e dos fios.',subtitleColor:'#014744',
    boxes:[defaultBox()],bodyCopy:'Estimular o crescimento dos fios\nMelhorar a circulação sanguínea\nAumentar a absorção de ativos\nFortalecer fios enfraquecidos\nRecuperar a densidade capilar\nReduzir queda\nEstimular regeneração tecidual\nMelhorar aparência de cicatrizes',bodyIsList:true,bodyColor:'#014744',
    image:{src:'assets/modelo1/layer-16.png',offsetX:0,offsetY:0,zoom:1}
  };
  const clone=o=>JSON.parse(JSON.stringify(o));
  const deepMerge=(base,patch)=>{const out=clone(base);for(const [k,v] of Object.entries(patch||{})){if(Array.isArray(v))out[k]=clone(v);else if(v&&typeof v==='object'&&out[k]&&typeof out[k]==='object'&&!Array.isArray(out[k]))out[k]=deepMerge(out[k],v);else out[k]=v}return out};
  const readProjects=()=>{try{const x=JSON.parse(localStorage.getItem(PROJECTS_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return []}};
  const writeProjects=x=>localStorage.setItem(PROJECTS_KEY,JSON.stringify(x));
  const newId=()=>`modelo1-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
  const projectRecord=id=>readProjects().find(p=>p.id===id);
  function loadInitial(){try{if(currentProjectId){const p=projectRecord(currentProjectId),d=localStorage.getItem(PROJECT_DRAFT_PREFIX+currentProjectId);return deepMerge(defaults,d?JSON.parse(d):(p?.state||{}))}const d=localStorage.getItem(DRAFT_KEY);return d?deepMerge(defaults,JSON.parse(d)):clone(defaults)}catch{return clone(defaults)}}
  let state=loadInitial(); state.fileName='Modelo 1'; if(!Array.isArray(state.boxes)||!state.boxes.length)state.boxes=[defaultBox()];

  const $=id=>document.getElementById(id);
  const els={title:$('title'),titleSize:$('titleSize'),titleSizeOut:$('titleSizeOut'),titleAutoFit:$('titleAutoFit'),titleColor:$('titleColor'),titleAccentColor:$('titleAccentColor'),subtitle:$('subtitle'),subtitleColor:$('subtitleColor'),bodyCopy:$('bodyCopy'),bodyIsList:$('bodyIsList'),bodyColor:$('bodyColor'),boxEditors:$('boxEditors'),addBox:$('addBox'),imageUpload:$('imageUpload'),imageZoom:$('imageZoom'),imageZoomOut:$('imageZoomOut'),resetImage:$('resetImage'),exportFormat:$('exportFormat'),exportFile:$('exportFile'),saveProject:$('saveProject'),duplicateProject:$('duplicateProject'),projectFeedback:$('projectFeedback'),design:$('design'),stageWrap:document.querySelector('.stage-wrap'),previewTitle:$('previewTitle'),previewSubtitle:$('previewSubtitle'),previewBoxes:$('previewBoxes'),lowerFlow:$('lowerFlow'),previewBodyCopy:$('previewBodyCopy'),imageMask:$('imageMask'),previewImage:$('previewImage')};

  function svgIcon(name){const icon=ICONS.find(i=>i.name===name)||ICONS[0];return `<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="${icon.path}"/></svg>`}
  function paletteSwatches(host,value,onPick){host.innerHTML='';for(const c of PALETTE){const b=document.createElement('button');b.type='button';b.className='swatch'+(value===c.value?' is-selected':'');b.style.background=c.value;b.title=c.name;b.addEventListener('click',()=>onPick(c.value));host.appendChild(b)}}
  function renderColorControls(){paletteSwatches(els.titleColor,state.titleColor,v=>{state.titleColor=v;commit()});paletteSwatches(els.titleAccentColor,state.titleAccentColor,v=>{state.titleAccentColor=v;commit()});paletteSwatches(els.subtitleColor,state.subtitleColor,v=>{state.subtitleColor=v;commit()});paletteSwatches(els.bodyColor,state.bodyColor,v=>{state.bodyColor=v;commit()})}
  function persist(){try{localStorage.setItem(currentProjectId?PROJECT_DRAFT_PREFIX+currentProjectId:DRAFT_KEY,JSON.stringify({...state,updatedAt:new Date().toISOString()}));els.projectFeedback.textContent='Alterações salvas automaticamente.'}catch{els.projectFeedback.textContent='Alterações mantidas nesta sessão.'}}
  function commit(){renderPreview();persist()}
  function safeName(s){return String(s||'Modelo 1').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').toLowerCase()||'modelo-1'}
  function splitTitle(text){const parts=String(text||'').trim().split(/\s+/);if(parts.length<2)return {main:text,accent:''};return {main:parts.slice(0,-1).join(' ')+' ',accent:parts.at(-1)}}
  function fitTitle(){const node=els.previewTitle;let size=state.titleSize;node.style.fontSize=size+'px';if(state.titleAutoFit){while(size>28&&node.scrollWidth>node.clientWidth){size-=1;node.style.fontSize=size+'px'}}}
  function syncInputs(){els.title.value=state.title;els.titleSize.value=state.titleSize;els.titleSizeOut.textContent=state.titleSize+'px';els.titleAutoFit.checked=state.titleAutoFit;els.subtitle.value=state.subtitle;els.bodyCopy.value=state.bodyCopy;els.bodyIsList.checked=state.bodyIsList;els.imageZoom.value=state.image.zoom;els.imageZoomOut.textContent=Math.round(state.image.zoom*100)+'%';renderColorControls();renderBoxEditors()}
  function renderBoxEditors(){els.boxEditors.innerHTML='';state.boxes.forEach((box,index)=>{const wrap=document.createElement('section');wrap.className='box-editor';wrap.innerHTML=`<div class="box-editor-head"><strong>Box ${index+1}</strong><div class="icon-actions"><button type="button" class="mini duplicate">Duplicar</button>${state.boxes.length>1?'<button type="button" class="mini danger remove">Excluir</button>':''}</div></div><label class="field"><span>Título</span><input class="box-title" type="text"></label><label class="field"><span>Texto</span><textarea class="box-body" rows="5"></textarea></label><div class="palette-field"><span>Paleta do box</span><div class="palette-options"></div></div><label class="field"><span>Pesquisar ícone</span><input class="icon-search" type="search" placeholder="favorite, health, science..."><div class="icon-results"></div></label>`;
      wrap.querySelector('.box-title').value=box.title;wrap.querySelector('.box-body').value=box.body;
      wrap.querySelector('.box-title').addEventListener('input',e=>{box.title=e.target.value;commit()});wrap.querySelector('.box-body').addEventListener('input',e=>{box.body=e.target.value;commit()});
      const palettes=wrap.querySelector('.palette-options');Object.entries(BOX_PALETTES).forEach(([key,p])=>{const b=document.createElement('button');b.type='button';b.className='palette-card'+(box.palette===key?' is-selected':'');b.innerHTML=`<span class="palette-preview"><i style="background:${p.bg}"></i><i style="background:${p.title}"></i><i style="background:${p.text}"></i></span>${p.name}`;b.addEventListener('click',()=>{box.palette=key;renderBoxEditors();commit()});palettes.appendChild(b)});
      const search=wrap.querySelector('.icon-search'),results=wrap.querySelector('.icon-results');const paint=q=>{results.innerHTML='';const term=q.trim().toLowerCase();ICONS.filter(i=>!term||i.name.includes(term)||i.label.toLowerCase().includes(term)).forEach(icon=>{const b=document.createElement('button');b.type='button';b.className='icon-choice'+(box.icon===icon.name?' is-selected':'');b.title=icon.name;b.innerHTML=svgIcon(icon.name);b.addEventListener('click',()=>{box.icon=icon.name;paint(search.value);commit()});results.appendChild(b)})};paint('');search.addEventListener('input',()=>paint(search.value));
      wrap.querySelector('.duplicate').addEventListener('click',()=>{state.boxes.splice(index+1,0,clone(box));renderBoxEditors();commit()});wrap.querySelector('.remove')?.addEventListener('click',()=>{state.boxes.splice(index,1);renderBoxEditors();commit()});els.boxEditors.appendChild(wrap)})}

  function renderPreview(){
    const t=splitTitle(state.title);els.previewTitle.style.color=state.titleColor;els.previewTitle.style.setProperty('--title-accent',state.titleAccentColor);els.previewTitle.innerHTML=`<span>${escapeHtml(t.main)}<span class="accent">${escapeHtml(t.accent)}</span></span>`;fitTitle();
    els.previewSubtitle.textContent=state.subtitle;els.previewSubtitle.style.color=state.subtitleColor;
    els.previewBodyCopy.style.color=state.bodyColor;els.previewBodyCopy.innerHTML='';els.previewBodyCopy.classList.toggle('is-list',state.bodyIsList);const lines=String(state.bodyCopy||'').split('\n').filter(v=>v.trim());if(state.bodyIsList)lines.forEach(line=>{const d=document.createElement('div');d.className='body-line';d.innerHTML=`<span class="body-check">✓</span><span>${escapeHtml(line)}</span>`;els.previewBodyCopy.appendChild(d)});else els.previewBodyCopy.textContent=state.bodyCopy;
    els.previewBoxes.innerHTML='';state.boxes.forEach(box=>{const p=BOX_PALETTES[box.palette]||BOX_PALETTES.light,d=document.createElement('section');d.className='design-box';d.style.background=p.bg;d.innerHTML=`<div class="design-box-icon-wrap" style="background:${p.circle};color:${p.icon}">${svgIcon(box.icon)}</div><div class="design-box-copy"><h3 style="color:${p.title}">${escapeHtml(box.title)}</h3><p style="color:${p.text}">${escapeHtml(box.body)}</p></div>`;els.previewBoxes.appendChild(d)});
    requestAnimationFrame(layoutFlow);
    els.previewImage.src=state.image.src;els.previewImage.style.transform=`translate(${state.image.offsetX}px,${state.image.offsetY}px) scale(${state.image.zoom})`;els.imageZoomOut.textContent=Math.round(state.image.zoom*100)+'%';
  }
  function layoutFlow(){
    const subRect=els.previewSubtitle.getBoundingClientRect(), designRect=els.design.getBoundingClientRect(), scale=designRect.width/1080||1;const subHeight=subRect.height/scale;const boxTop=346+subHeight+32;els.previewBoxes.style.top=boxTop+'px';
    let lastBottom=boxTop;const boxNodes=[...els.previewBoxes.children];if(boxNodes.length){lastBottom=boxTop+boxNodes.reduce((sum,n,i)=>sum+n.getBoundingClientRect().height/scale+(i?43:0),0)}const lowerOffset=Math.max(0,lastBottom+43-1127);els.lowerFlow.style.setProperty('--lower-offset',lowerOffset+'px');els.design.style.height=(1920+lowerOffset)+'px';updateScale();
  }
  function updateScale(){const width=els.stageWrap.clientWidth||720,scale=Math.min(width/1080,1);els.design.style.transform=`scale(${scale})`;els.stageWrap.style.height=(parseFloat(els.design.style.height||'1920')*scale)+'px'}
  function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}

  function wire(){
    document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('is-active',x===btn));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('is-active',p.dataset.panelContent===btn.dataset.panel))}));
    const bind=(el,fn,event='input')=>el.addEventListener(event,e=>{fn(e.target);commit()});bind(els.title,e=>state.title=e.value);bind(els.titleSize,e=>{state.titleSize=+e.value;els.titleSizeOut.textContent=e.value+'px'});bind(els.titleAutoFit,e=>state.titleAutoFit=e.checked,'change');bind(els.subtitle,e=>state.subtitle=e.value);bind(els.bodyCopy,e=>state.bodyCopy=e.value);bind(els.bodyIsList,e=>state.bodyIsList=e.checked,'change');bind(els.imageZoom,e=>state.image.zoom=+e.value);
    els.addBox.addEventListener('click',()=>{state.boxes.push(defaultBox());renderBoxEditors();commit()});els.resetImage.addEventListener('click',()=>{state.image.offsetX=0;state.image.offsetY=0;state.image.zoom=1;els.imageZoom.value=1;commit()});els.imageUpload.addEventListener('change',handleImageUpload);
    els.saveProject.addEventListener('click',saveProject);els.duplicateProject.addEventListener('click',duplicateProject);els.exportFormat.addEventListener('change',()=>els.exportFile.textContent=`Baixar ${els.exportFormat.value.toUpperCase()}`);els.exportFile.addEventListener('click',exportFile);window.addEventListener('resize',updateScale);wireImageDrag();
  }
  function wireImageDrag(){let drag=null;els.imageMask.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,ox:state.image.offsetX,oy:state.image.offsetY};els.imageMask.setPointerCapture(e.pointerId)});els.imageMask.addEventListener('pointermove',e=>{if(!drag)return;const scale=els.design.getBoundingClientRect().width/1080||1;state.image.offsetX=drag.ox+(e.clientX-drag.x)/scale;state.image.offsetY=drag.oy+(e.clientY-drag.y)/scale;renderPreview()});const end=()=>{if(drag){drag=null;persist()}};els.imageMask.addEventListener('pointerup',end);els.imageMask.addEventListener('pointercancel',end)}
  async function handleImageUpload(e){const f=e.target.files?.[0];if(!f)return;const img=await fileToResizedDataURL(f,1400);state.image={src:img,offsetX:0,offsetY:0,zoom:1};els.imageZoom.value=1;commit()}
  function fileToResizedDataURL(file,max){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.9))};im.onerror=rej;im.src=r.result};r.onerror=rej;r.readAsDataURL(file)})}

  function saveProject(){try{if(!currentProjectId)currentProjectId=newId();const now=new Date().toISOString(),record={id:currentProjectId,template:'modelo1isa',title:'Modelo 1',fileName:'Modelo 1',preview:'assets/images/modelo1-preview.jpg',editor:`modelo-editor.html?project=${encodeURIComponent(currentProjectId)}`,savedAt:now,updatedAt:now,state:clone(state)};const items=readProjects(),i=items.findIndex(p=>p.id===currentProjectId);if(i>=0)items[i]=record;else items.unshift(record);writeProjects(items);localStorage.setItem(PROJECT_DRAFT_PREFIX+currentProjectId,JSON.stringify(state));history.replaceState({},'',`modelo-editor.html?project=${encodeURIComponent(currentProjectId)}`);flash(els.saveProject,'Salvo ✓');els.projectFeedback.textContent='Projeto “Modelo 1” salvo.';return currentProjectId}catch(e){els.projectFeedback.textContent='Erro ao salvar projeto.';console.error(e);return null}}
  function duplicateProject(){const source=currentProjectId||saveProject();if(!source)return;try{const id=newId(),now=new Date().toISOString(),copy=clone(state),record={id,template:'modelo1isa',title:'Modelo 1 - cópia',fileName:'Modelo 1 - cópia',preview:'assets/images/modelo1-preview.jpg',editor:`modelo-editor.html?project=${encodeURIComponent(id)}`,savedAt:now,updatedAt:now,duplicatedFrom:source,state:copy};const items=readProjects();items.unshift(record);writeProjects(items);currentProjectId=id;state=copy;localStorage.setItem(PROJECT_DRAFT_PREFIX+id,JSON.stringify(state));history.replaceState({},'',`modelo-editor.html?project=${encodeURIComponent(id)}`);flash(els.duplicateProject,'Cópia criada ✓');els.projectFeedback.textContent='Cópia criada sem alterar o projeto original.'}catch(e){els.projectFeedback.textContent='Erro ao duplicar projeto.';console.error(e)}}
  function flash(btn,text){const old=btn.dataset.old||btn.textContent;btn.dataset.old=old;btn.textContent=text;btn.classList.add('is-success');setTimeout(()=>{btn.textContent=old;btn.classList.remove('is-success')},1500)}

  function wrap(ctx,text,max){const out=[];String(text||'').split('\n').forEach(p=>{if(!p){out.push('');return}let line='';for(const w of p.split(/\s+/)){const test=line?line+' '+w:w;if(ctx.measureText(test).width<=max||!line)line=test;else{out.push(line);line=w}}if(line)out.push(line)});return out}
  function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
  function loadImg(src){return new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=src})}
  async function drawFixed(ctx,src,x,y,w,h){const im=await loadImg(src);ctx.drawImage(im,x,y,w,h)}
  function drawTextLines(ctx,lines,x,y,lh){lines.forEach((l,i)=>ctx.fillText(l,x,y+i*lh));return lines.length*lh}
  async function renderCanvas(){await document.fonts.ready;layoutFlow();const lower=parseFloat(getComputedStyle(els.lowerFlow).getPropertyValue('--lower-offset'))||0,c=document.createElement('canvas');c.width=1080;c.height=1920+lower;const ctx=c.getContext('2d');ctx.fillStyle='#F3F0EB';ctx.fillRect(0,0,c.width,c.height);await drawFixed(ctx,'assets/modelo1/layer-2.png',67,149,96,10);await drawFixed(ctx,'assets/modelo1/layer-4.png',632,99,384,110);
    const title=splitTitle(state.title);let size=state.titleSize;ctx.textAlign='center';ctx.font=`italic 600 ${size}px "Cormorant Garamond",serif`;while(state.titleAutoFit&&size>28&&ctx.measureText(state.title).width>949){size--;ctx.font=`italic 600 ${size}px "Cormorant Garamond",serif`}const y=314;const mainW=ctx.measureText(title.main).width,accW=ctx.measureText(title.accent).width,total=mainW+accW,start=540-total/2;ctx.textAlign='left';ctx.fillStyle=state.titleColor;ctx.fillText(title.main,start,y);ctx.fillStyle=state.titleAccentColor;ctx.fillText(title.accent,start+mainW,y);
    ctx.font='400 18px Arial';ctx.fillStyle=state.subtitleColor;ctx.textAlign='center';const sub=wrap(ctx,state.subtitle,755),subY=360,subLH=20;sub.forEach((l,i)=>ctx.fillText(l,540,subY+i*subLH));let boxY=346+Math.max(48,sub.length*subLH)+32;
    for(const box of state.boxes){const p=BOX_PALETTES[box.palette]||BOX_PALETTES.light;ctx.font='400 33px Arial';const titleLines=wrap(ctx,box.title,690);ctx.font='400 18px Arial';const bodyLines=wrap(ctx,box.body,690);const h=Math.max(265,58+titleLines.length*36+35+bodyLines.length*22+58);ctx.fillStyle=p.bg;roundRect(ctx,64,boxY,954,h,24);ctx.fillStyle=p.circle;ctx.beginPath();ctx.arc(182,boxY+h/2,89,0,Math.PI*2);ctx.fill();const icon=ICONS.find(i=>i.name===box.icon)||ICONS[0],svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="94" height="94" fill="${p.icon}"><path d="${icon.path}"/></svg>`,im=await loadImg('data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg));ctx.drawImage(im,135,boxY+h/2-47,94,94);ctx.textAlign='left';ctx.fillStyle=p.title;ctx.font='400 33px Arial';drawTextLines(ctx,titleLines,294,boxY+69,36);ctx.fillStyle=p.text;ctx.font='400 18px Arial';drawTextLines(ctx,bodyLines,294,boxY+69+titleLines.length*36+35,22);boxY+=h+43}
    const lastBottom=boxY-43,low=Math.max(0,lastBottom+43-1127);await drawFixed(ctx,'assets/modelo1/layer-7.png',107,1127+low,470,60);ctx.fillStyle=state.bodyColor;ctx.font='400 17px Arial';ctx.textAlign='left';let by=1230+low;const bodyLines=String(state.bodyCopy||'').split('\n').filter(x=>x.trim());if(state.bodyIsList){for(const line of bodyLines){ctx.font='700 17px Arial';ctx.fillText('✓',74,by);ctx.font='400 17px Arial';ctx.fillText(line,97,by);by+=20}}else{ctx.font='400 17px Arial';drawTextLines(ctx,wrap(ctx,state.bodyCopy,544),74,by,20)}
    const mask=await loadImg('assets/modelo1/layer-15.png'),photo=await loadImg(state.image.src),off=document.createElement('canvas');off.width=449;off.height=725;const ox=off.getContext('2d');const cover=Math.max(449/photo.width,725/photo.height),dw=photo.width*cover*state.image.zoom,dh=photo.height*cover*state.image.zoom;ox.drawImage(photo,(449-dw)/2+state.image.offsetX,(725-dh)/2+state.image.offsetY,dw,dh);ox.globalCompositeOperation='destination-in';ox.drawImage(mask,0,0,449,725);ctx.drawImage(off,680,1131+low);await drawFixed(ctx,'assets/modelo1/layer-17.png',691,1129+low,438,415);for(const [src,x,yy,w,h] of [['6',106,1575,509,89],['9',76,1576,20,19],['18',0,1783,1080,137],['19',394,1751,292,19],['20',284,1855,557,17],['21',663,1810,194,24],['22',613,1803,37,37],['23',223,1809,269,24],['24',166,1802,39,39],['25',240,1850,30,30]])await drawFixed(ctx,`assets/modelo1/layer-${src}.png`,x,yy+low,w,h);return c}
  function dl(blob,name){const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
  function toBlob(c,type,q){return new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('Falha ao exportar')),type,q))}
  function jpegPdf(jpeg,w,h){const enc=s=>new TextEncoder().encode(s),parts=[],offs=[0];let pos=0;const push=b=>{parts.push(b);pos+=b.length},obj=(n,arr)=>{offs[n]=pos;push(enc(`${n} 0 obj\n`));arr.forEach(p=>push(typeof p==='string'?enc(p):p));push(enc('\nendobj\n'))};push(enc('%PDF-1.4\n'));obj(1,['<< /Type /Catalog /Pages 2 0 R >>']);obj(2,['<< /Type /Pages /Kids [3 0 R] /Count 1 >>']);const pw=405,ph=pw*h/w;obj(3,[`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pw} ${ph}] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>`]);obj(4,[`<< /Type /XObject /Subtype /Image /Width ${w} /Height ${h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`,jpeg,'\nendstream']);const s=`q\n${pw} 0 0 ${ph} 0 0 cm\n/Im0 Do\nQ\n`;obj(5,[`<< /Length ${s.length} >>\nstream\n${s}endstream`]);const x=pos;push(enc('xref\n0 6\n0000000000 65535 f \n'));for(let i=1;i<=5;i++)push(enc(`${String(offs[i]).padStart(10,'0')} 00000 n \n`));push(enc(`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`));return new Blob(parts,{type:'application/pdf'})}
  async function exportFile(){els.exportFile.disabled=true;try{const c=await renderCanvas(),fmt=els.exportFormat.value,base=safeName(currentProjectId&&projectRecord(currentProjectId)?.title||'Modelo 1');if(fmt==='png')dl(await toBlob(c,'image/png',1),base+'.png');else if(fmt==='jpg')dl(await toBlob(c,'image/jpeg',.95),base+'.jpg');else{const b=await toBlob(c,'image/jpeg',.95),arr=new Uint8Array(await b.arrayBuffer());dl(jpegPdf(arr,c.width,c.height),base+'.pdf')}}catch(e){alert('Não foi possível exportar: '+e.message)}finally{els.exportFile.disabled=false;els.exportFile.textContent=`Baixar ${els.exportFormat.value.toUpperCase()}`}}

  syncInputs();wire();renderPreview();updateScale();persist();
})();
