(() => {
'use strict';
const S=window.ProjectStorage;
const params=new URLSearchParams(location.search);let currentProjectId=params.get('project');
const PALETTE=[['Verde petróleo','#014744'],['Verde médio','#5B7E4E'],['Verde suave','#C4C9B3'],['Grafite','#262E34'],['Creme','#F3F0EB']];
const BOX_PALETTES={light:{name:'Claro',bg:'#DFDDD2',title:'#014744',text:'#262E34',circle:'#C4C9B3',icon:'#fff'},dark:{name:'Escuro',bg:'#014744',title:'#C4C9B3',text:'#F3F0EB',circle:'#5B7E4E',icon:'#F3F0EB'}};
const ICONS=[
['favorite','Coração','M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09A6.01 6.01 0 0 1 16.5 3C19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54z'],
['check_circle','Check','M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zm-2 15-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z'],
['health_and_safety','Saúde','M12 2 4 5v6c0 5.05 3.41 9.76 8 11 4.59-1.24 8-5.95 8-11V5l-8-3zm4 11h-3v3h-2v-3H8v-2h3V8h2v3h3v2z'],
['medical_services','Médico','M19 6h-3V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v2H5a3 3 0 0 0-3 3v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a3 3 0 0 0-3-3zm-9-2h4v2h-4V4zm5 10h-2v2h-2v-2H9v-2h2v-2h2v2h2v2z'],
['science','Ciência','M9 2v2h1v5.59l-5.7 7.32A3.2 3.2 0 0 0 6.82 22h10.36a3.2 3.2 0 0 0 2.52-5.09L14 9.59V4h1V2H9zm3 9.1 2.25 2.9h-4.5L12 11.1z'],
['spa','Spa','M12 21c-4.42 0-8-3.58-8-8 4.42 0 8 3.58 8 8zm0 0c0-4.42 3.58-8 8-8 0 4.42-3.58 8-8 8zm0-8c-2.76 0-5-2.24-5-5 2.76 0 5 2.24 5 5zm0 0c0-2.76 2.24-5 5-5 0 2.76-2.24 5-5 5z'],
['eco','Folha','M17.5 3C12 3 7.5 5 5 9c-2 3.2-1.4 7.2 1.4 9.5C9.2 20.8 13.2 20 15 17c2.6-4.2 1.7-9.7 2.5-14zM7 17c2-5 5-8 9-11-3 4-5 7-6 12l-3-1z'],
['water_drop','Gota','M12 2s-7 7.24-7 12a7 7 0 0 0 14 0c0-4.76-7-12-7-12zm0 16a4 4 0 0 1-4-4c0-.78.32-1.72.82-2.7A6 6 0 0 0 15 17.18 3.98 3.98 0 0 1 12 18z']
].map(([name,label,path])=>({name,label,path}));
const defaultBox=()=>({titleHtml:'O que é?',bodyHtml:'É um procedimento minimamente invasivo que cria microperfurações controladas no couro cabeludo para estimular a regeneração tecidual e potencializar a absorção de ativos.',palette:'light',icon:'favorite'});
const defaults={version:3,fileName:'Modelo 1',titleHtml:'Microagulhamento na <span style="color:#5B7E4E">Tricologia</span>',titleSize:58,titleAutoFit:true,subtitleHtml:'Uma técnica minimamente invasiva que promove estímulos importantes para a saúde do couro cabeludo e dos fios.',boxes:[defaultBox()],bodyHtml:'Estimular o crescimento dos fios<br>Melhorar a circulação sanguínea<br>Aumentar a absorção de ativos<br>Fortalecer fios enfraquecidos<br>Recuperar a densidade capilar<br>Reduzir queda<br>Estimular regeneração tecidual<br>Melhorar aparência de cicatrizes',bodyIsList:true,image:{src:'assets/modelo1/layer-16.png',offsetX:0,offsetY:0,zoom:1}};
const clone=o=>JSON.parse(JSON.stringify(o));
const merge=(a,b)=>{const o=clone(a);for(const[k,v]of Object.entries(b||{})){if(Array.isArray(v))o[k]=clone(v);else if(v&&typeof v==='object'&&o[k]&&typeof o[k]==='object'&&!Array.isArray(o[k]))o[k]=merge(o[k],v);else o[k]=v}return o};
function migrate(x){x=merge(defaults,x||{});if(x.title&&!x.titleHtml)x.titleHtml=esc(x.title);if(x.subtitle&&!x.subtitleHtml)x.subtitleHtml=esc(x.subtitle);if(x.bodyCopy&&!x.bodyHtml)x.bodyHtml=esc(x.bodyCopy).replace(/\n/g,'<br>');x.boxes=(x.boxes||[defaultBox()]).map(b=>({...defaultBox(),...b,titleHtml:b.titleHtml||esc(b.title||'O que é?'),bodyHtml:b.bodyHtml||esc(b.body||'')}));x.fileName='Modelo 1';return x}
const projectKey=id=>`modelo1:project:${id}`,draftKey=()=>currentProjectId?projectKey(currentProjectId):'modelo1:draft';
function readProjects(){return S?.getProjects?.()||[]}
function projectRecord(id){return readProjects().find(p=>p.id===id)}
function load(){const p=currentProjectId?projectRecord(currentProjectId):null;const d=S?.get(draftKey(),null);return migrate(d||(p?.state)||defaults)}
let state=load();
const $=id=>document.getElementById(id);const els={title:$('title'),titleSize:$('titleSize'),titleSizeOut:$('titleSizeOut'),titleAutoFit:$('titleAutoFit'),subtitle:$('subtitle'),bodyCopy:$('bodyCopy'),bodyIsList:$('bodyIsList'),boxEditors:$('boxEditors'),addBox:$('addBox'),imageUpload:$('imageUpload'),imageZoom:$('imageZoom'),imageZoomOut:$('imageZoomOut'),resetImage:$('resetImage'),exportFormat:$('exportFormat'),exportFile:$('exportFile'),saveProject:$('saveProject'),duplicateProject:$('duplicateProject'),projectFeedback:$('projectFeedback'),design:$('design'),stageWrap:document.querySelector('.stage-wrap'),previewTitle:$('previewTitle'),previewSubtitle:$('previewSubtitle'),previewBoxes:$('previewBoxes'),lowerFlow:$('lowerFlow'),previewBodyCopy:$('previewBodyCopy'),imageMask:$('imageMask'),previewImage:$('previewImage')};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function svgIcon(name){const i=ICONS.find(x=>x.name===name)||ICONS[0];return `<svg viewBox="0 0 24 24" fill="currentColor"><path d="${i.path}"/></svg>`}
function persist(){S?.set(draftKey(),{...state,updatedAt:new Date().toISOString()});els.projectFeedback.textContent=S?.persistent?'Alterações salvas automaticamente.':'Alterações preservadas nesta aba; use Salvar projeto.'}
function commit(){renderPreview();persist()}

// Rich text selection toolbar
const savedRanges=new WeakMap();
function saveRange(ed){const sel=getSelection();if(!sel?.rangeCount)return;const r=sel.getRangeAt(0);if(ed.contains(r.commonAncestorContainer))savedRanges.set(ed,r.cloneRange())}
function applyStyle(ed,prop,val,onChange){let r=savedRanges.get(ed);if(!r||r.collapsed){els.projectFeedback.textContent='Selecione um trecho do texto primeiro.';return}const span=document.createElement('span');span.style[prop]=val;try{span.appendChild(r.extractContents());r.insertNode(span);const sel=getSelection();sel.removeAllRanges();const nr=document.createRange();nr.selectNodeContents(span);sel.addRange(nr);savedRanges.set(ed,nr.cloneRange());onChange(ed.innerHTML);commit()}catch(e){console.error(e)}}
function toolbarHTML(){return `<div class="rt-colors">${PALETTE.map(([n,v])=>`<button type="button" class="rt-swatch" data-color="${v}" title="${n}" style="background:${v}"></button>`).join('')}</div><select class="rt-weight" title="Peso"><option value="400">Regular</option><option value="500">Medium</option><option value="600">Semibold</option><option value="700">Bold</option></select><select class="rt-size" title="Tamanho"><option value="14px">14</option><option value="16px">16</option><option value="18px" selected>18</option><option value="20px">20</option><option value="24px">24</option><option value="28px">28</option><option value="32px">32</option><option value="40px">40</option><option value="48px">48</option><option value="58px">58</option><option value="64px">64</option><option value="72px">72</option></select>`}
function wireRich(ed,toolbar,onChange){toolbar.innerHTML=toolbarHTML();['mouseup','keyup','focus','input'].forEach(ev=>ed.addEventListener(ev,()=>{saveRange(ed);if(ev==='input'){onChange(ed.innerHTML);commit()}}));toolbar.querySelectorAll('.rt-swatch').forEach(b=>b.addEventListener('mousedown',e=>{e.preventDefault();applyStyle(ed,'color',b.dataset.color,onChange)}));const w=toolbar.querySelector('.rt-weight'),z=toolbar.querySelector('.rt-size');[w,z].forEach(x=>x.addEventListener('pointerdown',()=>saveRange(ed)));w.addEventListener('change',()=>applyStyle(ed,'fontWeight',w.value,onChange));z.addEventListener('change',()=>applyStyle(ed,'fontSize',z.value,onChange))}
function wireStaticRich(){wireRich(els.title,document.querySelector('[data-toolbar-for="title"]'),v=>state.titleHtml=v);wireRich(els.subtitle,document.querySelector('[data-toolbar-for="subtitle"]'),v=>state.subtitleHtml=v);wireRich(els.bodyCopy,document.querySelector('[data-toolbar-for="bodyCopy"]'),v=>state.bodyHtml=v)}

function renderBoxEditors(){els.boxEditors.innerHTML='';state.boxes.forEach((box,index)=>{const w=document.createElement('section');w.className='box-editor';w.innerHTML=`<div class="box-editor-head"><strong>Box ${index+1}</strong><div class="icon-actions"><button type="button" class="mini duplicate">Duplicar</button>${state.boxes.length>1?'<button type="button" class="mini danger remove">Excluir</button>':''}</div></div><div class="field rich-field"><span>Título</span><div class="rich-input box-title" contenteditable="true"></div><div class="rich-toolbar title-toolbar"></div></div><div class="field rich-field"><span>Texto</span><div class="rich-input rich-input-tall box-body" contenteditable="true"></div><div class="rich-toolbar body-toolbar"></div></div><div class="palette-field"><span>Paleta do box</span><div class="palette-options"></div></div><label class="field"><span>Pesquisar ícone</span><input class="icon-search" type="search" placeholder="saúde, coração, ciência..."><div class="icon-results"></div></label>`;
const te=w.querySelector('.box-title'),be=w.querySelector('.box-body');te.innerHTML=box.titleHtml;be.innerHTML=box.bodyHtml;wireRich(te,w.querySelector('.title-toolbar'),v=>box.titleHtml=v);wireRich(be,w.querySelector('.body-toolbar'),v=>box.bodyHtml=v);
const po=w.querySelector('.palette-options');Object.entries(BOX_PALETTES).forEach(([k,p])=>{const b=document.createElement('button');b.type='button';b.className='palette-card'+(box.palette===k?' is-selected':'');b.innerHTML=`<span class="palette-preview"><i style="background:${p.bg}"></i><i style="background:${p.title}"></i><i style="background:${p.text}"></i></span>${p.name}`;b.onclick=()=>{box.palette=k;renderBoxEditors();commit()};po.appendChild(b)});
const search=w.querySelector('.icon-search'),res=w.querySelector('.icon-results');const paint=q=>{res.innerHTML='';ICONS.filter(i=>!q||i.name.includes(q.toLowerCase())||i.label.toLowerCase().includes(q.toLowerCase())).forEach(i=>{const b=document.createElement('button');b.type='button';b.className='icon-choice'+(box.icon===i.name?' is-selected':'');b.title=i.label;b.innerHTML=svgIcon(i.name);b.onclick=()=>{box.icon=i.name;paint(search.value);commit()};res.appendChild(b)})};paint('');search.oninput=()=>paint(search.value);w.querySelector('.duplicate').onclick=()=>{state.boxes.splice(index+1,0,clone(box));renderBoxEditors();commit()};w.querySelector('.remove')?.addEventListener('click',()=>{state.boxes.splice(index,1);renderBoxEditors();commit()});els.boxEditors.appendChild(w)})}
function syncInputs(){els.title.innerHTML=state.titleHtml;els.titleSize.value=state.titleSize;els.titleSizeOut.textContent=state.titleSize+'px';els.titleAutoFit.checked=state.titleAutoFit;els.subtitle.innerHTML=state.subtitleHtml;els.bodyCopy.innerHTML=state.bodyHtml;els.bodyIsList.checked=state.bodyIsList;els.imageZoom.value=state.image.zoom;els.imageZoomOut.textContent=Math.round(state.image.zoom*100)+'%';renderBoxEditors()}
function htmlLines(html){const d=document.createElement('div');d.innerHTML=html;const out=[];let cur='';const flush=()=>{if(cur.trim()||!out.length){out.push(cur);cur=''}};function walk(n){if(n.nodeType===3){cur+=esc(n.nodeValue)}else if(n.nodeType===1){const tag=n.tagName;const style=n.getAttribute('style');if(['DIV','P'].includes(tag)&&cur)flush();if(tag==='BR'){flush();return}const open=style?`<span style="${style.replace(/"/g,'&quot;')}">`:'';if(open)cur+=open;[...n.childNodes].forEach(walk);if(open)cur+='</span>';if(['DIV','P'].includes(tag))flush()}}[...d.childNodes].forEach(walk);if(cur||!out.length)flush();return out.filter((x,i,a)=>x.trim()||a.length===1)}
function renderPreview(){els.previewTitle.innerHTML=state.titleHtml;els.previewTitle.style.fontSize=state.titleSize+'px';fitTitle();els.previewSubtitle.innerHTML=state.subtitleHtml;els.previewBodyCopy.innerHTML='';els.previewBodyCopy.classList.toggle('is-list',state.bodyIsList);if(state.bodyIsList)htmlLines(state.bodyHtml).forEach(line=>{const d=document.createElement('div');d.className='body-line';d.innerHTML=`<span class="body-check">✓</span><span>${line}</span>`;els.previewBodyCopy.appendChild(d)});else els.previewBodyCopy.innerHTML=state.bodyHtml;els.previewBoxes.innerHTML='';state.boxes.forEach(box=>{const p=BOX_PALETTES[box.palette]||BOX_PALETTES.light,d=document.createElement('section');d.className='design-box';d.style.background=p.bg;d.innerHTML=`<div class="design-box-icon-wrap" style="background:${p.circle};color:${p.icon}">${svgIcon(box.icon)}</div><div class="design-box-copy"><h3 style="color:${p.title}">${box.titleHtml}</h3><div class="box-body-preview" style="color:${p.text}">${box.bodyHtml}</div></div>`;els.previewBoxes.appendChild(d)});els.previewImage.src=state.image.src;els.previewImage.style.transform=`translate(${state.image.offsetX}px,${state.image.offsetY}px) scale(${state.image.zoom})`;els.imageZoomOut.textContent=Math.round(state.image.zoom*100)+'%';requestAnimationFrame(layoutFlow)}
function fitTitle(){let z=state.titleSize;els.previewTitle.style.fontSize=z+'px';if(state.titleAutoFit){while(z>28&&els.previewTitle.scrollWidth>els.previewTitle.clientWidth){z--;els.previewTitle.style.fontSize=z+'px'}}}
function layoutFlow(){const s=els.design.getBoundingClientRect().width/1080||1,sh=els.previewSubtitle.getBoundingClientRect().height/s,boxTop=346+sh+32;els.previewBoxes.style.top=boxTop+'px';let bottom=boxTop;[...els.previewBoxes.children].forEach((n,i)=>bottom+=n.getBoundingClientRect().height/s+(i?43:0));const lower=Math.max(0,bottom+43-1127);els.lowerFlow.style.setProperty('--lower-offset',lower+'px');els.design.style.height='1920px';updateScale();if(1920+lower>1920)els.projectFeedback.textContent=lower>0?'Conteúdo mantido em 1080 × 1920; revise boxes extras para evitar corte no rodapé.':els.projectFeedback.textContent}
function updateScale(){const sc=Math.min((els.stageWrap.clientWidth||720)/1080,1);els.design.style.transform=`scale(${sc})`;els.stageWrap.style.height=1920*sc+'px'}
function newId(){return `modelo1-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`}
function saveProject(){try{if(!currentProjectId)currentProjectId=newId();const now=new Date().toISOString(),rec={id:currentProjectId,template:'modelo1isa',title:'Modelo 1',fileName:'Modelo 1',preview:'assets/images/modelo1-preview.jpg',editor:`modelo-editor.html?project=${encodeURIComponent(currentProjectId)}`,savedAt:projectRecord(currentProjectId)?.savedAt||now,updatedAt:now,state:clone(state)};const arr=readProjects(),i=arr.findIndex(p=>p.id===currentProjectId);if(i>=0)arr[i]=rec;else arr.unshift(rec);S.setProjects(arr);S.set(projectKey(currentProjectId),clone(state));history.replaceState({},'',`modelo-editor.html?project=${encodeURIComponent(currentProjectId)}`);flash(els.saveProject,'Salvo ✓');els.projectFeedback.textContent='Projeto salvo e disponível no index.';return currentProjectId}catch(e){console.error(e);els.projectFeedback.textContent='Erro ao salvar projeto.';return null}}
function duplicateProject(){const source=currentProjectId||saveProject();if(!source)return;const id=newId(),now=new Date().toISOString(),copy=clone(state),rec={id,template:'modelo1isa',title:'Modelo 1 - cópia',fileName:'Modelo 1 - cópia',preview:'assets/images/modelo1-preview.jpg',editor:`modelo-editor.html?project=${encodeURIComponent(id)}`,savedAt:now,updatedAt:now,duplicatedFrom:source,state:copy};const arr=readProjects();arr.unshift(rec);S.setProjects(arr);S.set(projectKey(id),copy);currentProjectId=id;history.replaceState({},'',`modelo-editor.html?project=${encodeURIComponent(id)}`);flash(els.duplicateProject,'Cópia criada ✓');els.projectFeedback.textContent='Cópia criada. O original foi preservado.'}
function flash(b,t){const o=b.dataset.old||b.textContent;b.dataset.old=o;b.textContent=t;b.classList.add('is-success');setTimeout(()=>{b.textContent=o;b.classList.remove('is-success')},1400)}
function safeName(s){return String(s||'Modelo 1').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').toLowerCase()||'modelo-1'}
function fileToResizedDataURL(file,max){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.9))};im.onerror=rej;im.src=r.result};r.onerror=rej;r.readAsDataURL(file)})}
async function handleImageUpload(e){const f=e.target.files?.[0];if(!f)return;state.image={src:await fileToResizedDataURL(f,1400),offsetX:0,offsetY:0,zoom:1};els.imageZoom.value=1;commit()}
function wireImageDrag(){let d=null;els.imageMask.onpointerdown=e=>{d={x:e.clientX,y:e.clientY,ox:state.image.offsetX,oy:state.image.offsetY};els.imageMask.setPointerCapture(e.pointerId)};els.imageMask.onpointermove=e=>{if(!d)return;const sc=els.design.getBoundingClientRect().width/1080||1;state.image.offsetX=d.ox+(e.clientX-d.x)/sc;state.image.offsetY=d.oy+(e.clientY-d.y)/sc;renderPreview()};els.imageMask.onpointerup=els.imageMask.onpointercancel=()=>{if(d){d=null;persist()}}}
function wire(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('is-active',x===b));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('is-active',p.dataset.panelContent===b.dataset.panel))});els.titleSize.oninput=e=>{state.titleSize=+e.target.value;els.titleSizeOut.textContent=e.target.value+'px';commit()};els.titleAutoFit.onchange=e=>{state.titleAutoFit=e.target.checked;commit()};els.bodyIsList.onchange=e=>{state.bodyIsList=e.target.checked;commit()};els.imageZoom.oninput=e=>{state.image.zoom=+e.target.value;commit()};els.addBox.onclick=()=>{state.boxes.push(defaultBox());renderBoxEditors();commit()};els.resetImage.onclick=()=>{state.image.offsetX=0;state.image.offsetY=0;state.image.zoom=1;els.imageZoom.value=1;commit()};els.imageUpload.onchange=handleImageUpload;els.saveProject.onclick=saveProject;els.duplicateProject.onclick=duplicateProject;els.exportFormat.onchange=()=>els.exportFile.textContent=`Baixar ${els.exportFormat.value.toUpperCase()}`;els.exportFile.onclick=exportFile;addEventListener('resize',updateScale);wireImageDrag();wireStaticRich()}

// DOM-to-image export at original PSD dimensions only: 1080 × 1920.
async function blobDataURL(url){const r=await fetch(url);const b=await r.blob();return await new Promise((res,rej)=>{const f=new FileReader();f.onload=()=>res(f.result);f.onerror=rej;f.readAsDataURL(b)})}
async function renderCanvas(){await document.fonts.ready;const cloneNode=els.design.cloneNode(true);cloneNode.style.transform='none';cloneNode.style.width='1080px';cloneNode.style.height='1920px';cloneNode.style.position='relative';cloneNode.querySelectorAll('img').forEach(i=>i.setAttribute('crossorigin','anonymous'));
const imgs=[...cloneNode.querySelectorAll('img')];await Promise.all(imgs.map(async i=>{try{if(i.src.startsWith('data:'))return;const src=i.getAttribute('src');i.src=await blobDataURL(src)}catch{}}));
const css=[...document.styleSheets].map(ss=>{try{return [...ss.cssRules].map(r=>r.cssText).join('\n')}catch{return''}}).join('\n');
const html=new XMLSerializer().serializeToString(cloneNode);const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920"><foreignObject width="1080" height="1920"><div xmlns="http://www.w3.org/1999/xhtml"><style>${css}</style>${html}</div></foreignObject></svg>`;const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const im=await new Promise((res,rej)=>{const x=new Image();x.onload=()=>res(x);x.onerror=rej;x.src=url});const c=document.createElement('canvas');c.width=1080;c.height=1920;c.getContext('2d').drawImage(im,0,0);return c}finally{URL.revokeObjectURL(url)}}
function toBlob(c,t,q){return new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('Falha ao exportar')),t,q))}
function dl(blob,name){const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1200)}
function jpegPdf(jpeg,w,h){const E=s=>new TextEncoder().encode(s),parts=[],offs=[0];let pos=0;const push=b=>{parts.push(b);pos+=b.length},obj=(n,a)=>{offs[n]=pos;push(E(`${n} 0 obj\n`));a.forEach(p=>push(typeof p==='string'?E(p):p));push(E('\nendobj\n'))};push(E('%PDF-1.4\n'));obj(1,['<< /Type /Catalog /Pages 2 0 R >>']);obj(2,['<< /Type /Pages /Kids [3 0 R] /Count 1 >>']);const pw=405,ph=pw*h/w;obj(3,[`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pw} ${ph}] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>`]);obj(4,[`<< /Type /XObject /Subtype /Image /Width ${w} /Height ${h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`,jpeg,'\nendstream']);const q=`q\n${pw} 0 0 ${ph} 0 0 cm\n/Im0 Do\nQ\n`;obj(5,[`<< /Length ${q.length} >>\nstream\n${q}endstream`]);const x=pos;push(E('xref\n0 6\n0000000000 65535 f \n'));for(let i=1;i<=5;i++)push(E(`${String(offs[i]).padStart(10,'0')} 00000 n \n`));push(E(`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`));return new Blob(parts,{type:'application/pdf'})}
async function exportFile(){els.exportFile.disabled=true;try{const c=await renderCanvas(),fmt=els.exportFormat.value,base=safeName(projectRecord(currentProjectId)?.title||'Modelo 1');if(fmt==='png')dl(await toBlob(c,'image/png',1),base+'.png');else if(fmt==='jpg')dl(await toBlob(c,'image/jpeg',.95),base+'.jpg');else{const b=await toBlob(c,'image/jpeg',.95);dl(jpegPdf(new Uint8Array(await b.arrayBuffer()),1080,1920),base+'.pdf')}}catch(e){console.error(e);alert('Não foi possível exportar: '+e.message)}finally{els.exportFile.disabled=false;els.exportFile.textContent=`Baixar ${els.exportFormat.value.toUpperCase()}`}}

syncInputs();wire();renderPreview();updateScale();persist();
})();
